apiVersion: v1
kind: Service
metadata:
  name: gecko-frontend
  labels:
    app: gecko
    role: ui
spec:
  type: NodePort
  selector:
    app: gecko
    role: ui
  ports:
  - port: 80
    nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gecko-frontend
  labels:
    app: gecko
    role: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gecko
      role: ui
  template:
    metadata:
      labels:
        app: gecko
        role: ui
    spec:
      imagePullSecrets:
      - name: geckofront
      containers:
      - name: ui
        image: gecko/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200