#Backend 
trigger:
- master

pr:
- master
- Main-Dev

pool:
  vmImage: ubuntu-latest

variables: #Path to folders
  sDir: 'WebAPI'
  solution: 'WebAPI/*.sln'

stages:
- stage: DotNet_Sonar
  jobs:
  #Prepare the sonar cloud
    - job: Scanner
      displayName: 'Run Sonar Analysis'
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'Insurance Scanner'
          organization: '210726-wvu-net-ext'
          scannerMode: 'MSBuild'
          projectKey: '210726-wvu-net-ext_Group2-P3-Pet_Insurance'
          projectName: 'Group2-P3-Pet_Insurance'
          extraProperties: 'sonar.exclusions=**/lib/**/*'
  #Build and test dotnet code
      # Force dotnet 5
      - task: UseDotNet@2
        displayName: Dotnet SDK 5
        inputs:
          packageType: 'sdk'
          version: '5.x'
      #Install nuGet
      - task: NuGetToolInstaller@1
        inputs:
          checkLatest: true
      #Restore solution
      - task: NuGetCommand@2
        inputs:
          restoreSolution: $(solution)
      #Build
      - task: CmdLine@2
        displayName: Dotnet Build
        inputs:
          script: 'dotnet build --configuration Release'
          workingDirectory: $(sDir)
      #Test
      - task: CmdLine@2
        displayName: Dotnet Tests
        inputs:
          script: 'dotnet test --configuration Release'
          workingDirectory: $(sDir)
      # Force dotnet 3.1
      - task: UseDotNet@2
        displayName: Dotnet SDK 3
        inputs:
          packageType: 'runtime'
          version: '3.1.x'
    #Analyze
      - task: SonarCloudAnalyze@1
        displayName: 'Run SonarCloud analysis'
    #Publish
      - task: SonarCloudPublish@1
        displayName: 'Publish results on build summary'
- stage: Docker
  jobs:
  #Build and eventally deploy a docker container
    - job: Docker_Build
      displayName: Docker Build
      steps:
      #Login
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker 1'
          command: 'login'
      #Build
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker 1'
          repository: 'ehart3/gecko'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      #logout
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker 1'
          command: 'logout'
