#Front End
trigger:
- master

pr:
- master
- Main-Dev

pool:
  vmImage: ubuntu-latest

variables: #Path to folders
  angular: '$(Build.SourcesDirectory)/Client'
  cReg: '2107-p3-acr-Group2-Pet Insurance'

stages:
- stage: Installs_Builds
  #Runs NPM Installs
  jobs:
    - job: Main
      displayName: Install_Build
      steps:
    #Install Node
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '14.x'
    #Install Angular
      - task: CmdLine@2
        displayName: Install Angular
        inputs:
          script: 'npm install -g @angular/cli'
          workingDirectory: $(angular)
    #Restore
      - task: CmdLine@2
        displayName: NPM CI
        inputs:
          script: 'npm ci'
          workingDirectory: $(angular)
    #Build Angular App
      - task: AngularCLI@1
        displayName: Angular Build
        inputs:
          command: 'build'
          project: '$(angular)'
          DisableAnalytics: false
- stage: Docker
  jobs:
  #Build and eventally deploy a docker container
    - job: Docker_Build
      displayName: Docker Build & Push
      steps:
      #Login
      - task: Docker@2
        displayName: Login
        inputs:
          containerRegistry: $(cReg)
          command: 'login'
      #Build
      - task: Docker@2
        displayName: Build & Push
        inputs:
          containerRegistry: '$(cReg)'
          repository: 'gecko/frontend'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
      #Publish artifact
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifest'
          publishLocation: 'Container'
      #logout
      - task: Docker@2
        displayName: Logout
        inputs:
          containerRegistry: $(cReg)
          command: 'logout'
