apiVersion: v1
kind: Service
metadata:
  name: gecko-backend
  labels:
    app: gecko
    role: api
spec:
  type: NodePort
  selector:
    app: gecko
    role: api
  ports:
  - port: 80
    nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gecko-backend
  labels:
    app: gecko
    role: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gecko
      role: api
  template:
    metadata:
      labels:
        app: gecko
        role: api
    spec:
      imagePullSecrets:
      - name: geckoback
      containers:
      - name: api
        image: gecko/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200